import java.util.Arrays;
import java.util.List;

public class Converter {
    public static void main(String[] args) {
        List<String> tables = Arrays.asList(
                "abilitazioni_impiantisti"
                , "access_logs"
                , "addetti"
                , "addetti_comuni"
                , "addetti_dipendenti_contratti"
                , "addetti_dipendenti_orari"
                , "addetti_dipendenti_qualifica"
                , "ateco_banca_dati"
                , "ateco_localizzazioni"
                , "banca_dati"
                , "banca_dati_note"
                , "bilanci_analisi"
                , "bilanci_analisi_medie"
                , "bilanci_banca_dati"
                , "bilanci_dettagli"
                , "cariche"
                , "catasto"
                , "collegate_banca_dati"
                , "collegate_esponenti"
                , "comunicazioni_curatore"
                , "configurations"
                , "dati_ditte_capitale"
                , "dati_economici"
                , "dati_identificativi"
                , "decodifica_attivita"
                , "ditte"
                , "domicilio_fiscale"
                , "email_logs"
                , "emails"
                , "estremi_atto"
                , "fallimento"
                , "familiari_partecipi"
                , "fido"
                , "flyway_schema_history"
                , "fusioni_eventi"
                , "fusioni_scissioni"
                , "gestione_monitoraggio"
                , "gestione_monitoraggio_log_events"
                , "gestione_monitoraggio_logs"
                , "ic_cciaas"
                , "ic_file_downloads"
                , "ic_legal_statuses"
                , "info_attivita"
                , "info_attivita_certificazioni"
                , "info_attivita_settori"
                , "info_sede"
                , "licenze"
                , "localizzazioni"
                , "marchi"
                , "marchi_note"
                , "nature_giuridiche"
                , "notification_events"
                , "notification_subscriptions"
                , "notification_types"
                , "notification_views"
                , "notizie"
                , "notizie_colore"
                , "partecipate"
                , "persone"
                , "persone_ditte"
                , "persone_rappresentanti"
                , "pregiudizievoli"
                , "pregiudizievoli_dettaglio"
                , "privileges"
                , "procedura_comunicazioni_curatore"
                , "procedure_concorsuali"
                , "produttori"
                , "produttori_bilanci"
                , "produttori_note"
                , "protesti"
                , "protesti_dettaglio"
                , "protesti_periodici_log_events"
                , "protesti_periodici_logs"
                , "protesto_similarity_rule_dettagli"
                , "protesto_similarity_rules"
                , "punti_vendita"
                , "punti_vendita_marchi"
                , "punti_vendita_note"
                , "punti_vendita_ordini"
                , "punti_vendita_rango"
                , "punti_vendita_rate"
                , "quote"
                , "richieste_giornaliere"
                , "richieste_giornaliere_events"
                , "rischio"
                , "rischio_score"
                , "roles"
                , "roles_privileges"
                , "ruoli_persona"
                , "sinistri"
                , "soci"
                , "soci_altri_diritti"
                , "source_audits"
                , "subentri"
                , "tipi_procedure_concorsuali"
                , "tipo_diritto"
                , "titoli_onorifici"
                , "trasferimenti_proprieta"
                , "trasferimenti_proprieta_titolari"
                , "trasferimenti_quote"
                , "trasferimento_riquadri"
                , "trasferimento_sede"
                , "trasferimento_titolari"
                , "users"
                , "users_roles"
                , "visura_audits");
        List<String> alterScripts = Arrays.asList(
                  "ALTER TABLE table_name ADD COLUMN created_by INTEGER;"
                , "ALTER TABLE table_name ADD COLUMN updated_by INTEGER;"
                , "ALTER TABLE table_name ADD CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES users (seriale) ON DELETE SET NULL;"
                , "ALTER TABLE table_name ADD CONSTRAINT fk_updated_by FOREIGN KEY (created_by) REFERENCES users (seriale) ON DELETE SET NULL;");
        StringBuilder sql = new StringBuilder();
        tables.forEach(tableName -> {
            sql.append("-- alter table " + tableName);
            sql.append(("\n"));
            alterScripts.forEach(alter -> {
                sql.append(alter.replace("table_name", tableName));
                sql.append(("\n"));
            });
        });

        System.out.println(sql);
    }
}
